name: 'Terraform Plan/Apply'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    if : ${{ (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~1.9.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::717340753727:role/cbe-blr-eks-ro-role
          role-session-name: terraform-github-actions
          aws-region: us-west-2
          mask-aws-account-id: false
          role-duration-seconds: 3600  # 1 hour

      - name: Terraform Init
        working-directory: tf-resources
        run: terraform init

      - name: Terraform Plan
        working-directory: tf-resources
        run: terraform plan
  
  terraform-apply:
    if : ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~1.9.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::717340753727:role/cbe-blr-eks-rw-role
          role-session-name: terraform-github-actions
          aws-region: us-west-2
          mask-aws-account-id: false
          role-duration-seconds: 3600  # 1 hour

      - name: Terraform Init
        working-directory: tf-resources
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        working-directory: tf-resources
        run: terraform apply -auto-approve

      - name: Terraform Apply RBAC
        if: ${{ github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        working-directory: tf-rbac
        run: |
          aws eks update-kubeconfig --name cbe-blr-eks-cluster --region us-west-2
          terraform init
          terraform plan
          terraform apply -auto-approve
